import { _electron as electron } from 'playwright';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import electronPath from 'electron';
import { useVietnamese } from './smoke-language.mjs';

const data = await mkdtemp(join(tmpdir(), 'orglet-desktop-'));
const output = resolve('test-results'); await mkdir(output, { recursive: true });
const env = { ...process.env, ORGLET_DATA_DIR: data }; delete env.ELECTRON_RUN_AS_NODE;
const launch = () => electron.launch({ executablePath: electronPath, args: ['.'], env, timeout: 30_000 });
let app;
const errors = [];
try {
  app = await launch();
  const page = await app.firstWindow(); page.on('pageerror', error => errors.push(error.message));
  await useVietnamese(page);
  const native = await app.evaluate(({ BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows()[0]; const prefs = window.webContents.getLastWebPreferences();
    return { title: window.getTitle(), visible: window.isVisible(), sandbox: prefs.sandbox, contextIsolation: prefs.contextIsolation, nodeIntegration: prefs.nodeIntegration, bounds: window.getBounds() };
  });
  assert.equal(native.title, 'Orglet'); assert.equal(native.visible, true); assert.equal(native.sandbox, true); assert.equal(native.contextIsolation, true); assert.equal(native.nodeIntegration, false);
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  const forbidden = join(data, 'outside-renderer.txt'); await writeFile(forbidden, 'Private fixture outside renderer');
  const exposed = await page.evaluate(async url => { try { return await (await fetch(url)).text(); } catch { return null; } }, pathToFileURL(forbidden).href);
  assert.equal(exposed, null, 'Renderer must not read arbitrary local files');
  await page.screenshot({ path: join(output, 'desktop-empty.png') });
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).fill('IME chưa hoàn tất');
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).evaluate(element => element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, isComposing: true })));
  assert.equal((await page.evaluate(() => window.orglet.call('workspace', {}))).tasks.length, 0);
  const sourcePath = join(data, 'evidence.txt'); await writeFile(sourcePath, 'Evidence fixture.\nSecond line.');
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, sourcePath);
  await page.getByRole('button', { name: 'Thêm nguồn', exact: true }).click(); await page.getByRole('menuitem', { name: /^Tệp/ }).click();
  await page.getByText('evidence.txt', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).fill('Desktop smoke: persistent task');
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).press('Shift+Enter');
  assert.equal((await page.evaluate(() => window.orglet.call('workspace', {}))).tasks.length, 0);
  await page.getByRole('button', { name: 'Gửi công việc', exact: true }).click();
  await page.locator('.chat-reply, .report').first().waitFor();
  // A chat answer has no accept step; it is kept like any message.
  await page.getByRole('button', { name: 'Sao chép', exact: true }).waitFor();
  const state = await page.evaluate(() => window.orglet.call('workspace', {}));
  const taskId = state.tasks[0].id; assert.equal(state.tasks[0].accepted, false);
  await page.screenshot({ path: join(output, 'desktop-report.png') });
  await page.getByRole('button', { name: 'Chi tiết', exact: true }).click();
  await page.getByRole('dialog').waitFor(); await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.waitForFunction(() => document.activeElement?.textContent === 'Chi tiết');
  await page.getByRole('button', { name: '1 nguồn', exact: true }).click();
  await page.getByRole('button', { name: 'Đọc nội dung', exact: true }).click();
  await page.getByText('Evidence fixture.', { exact: false }).waitFor();
  await page.screenshot({ path: join(output, 'desktop-source.png') });
  await page.getByRole('button', { name: 'Thu hồi quyền đọc', exact: true }).click();
  await page.getByText(/Đã thu hồi quyền đọc/).waitFor();
  assert.equal(await page.locator('.source-preview').count(), 0);
  await page.keyboard.press('Escape');
  const exported = join(data, 'report.md');
  await app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: path }); }, exported);
  await page.getByRole('button', { name: 'Tải xuống', exact: true }).first().click();
  await page.getByRole('menuitem', { name: 'Tải Markdown (.md)', exact: true }).click();
  // The export is written asynchronously after the save dialog resolves.
  for (let attempt = 0; attempt < 50 && !(await readFile(exported, 'utf8').catch(() => '')); attempt++) await new Promise(resolve => setTimeout(resolve, 100));
  // A chat answer downloads as the message itself.
  assert.match(await readFile(exported, 'utf8'), /nhân viên demo/);
  const fakeKeyPath = join(data, 'fixture-key.txt'); const fakeKey = 'sk-orglet-fixture-not-a-real-api-key'; await writeFile(fakeKeyPath, fakeKey);
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, fakeKeyPath);
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click();
  await page.getByRole('tab', { name: 'Kết nối API', exact: true }).click();
  const openaiRegion = page.getByRole('region', { name: 'Kết nối OpenAI', exact: true });
  await openaiRegion.getByRole('switch').click();
  await openaiRegion.getByRole('button', { name: 'Từ tệp', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Đã lưu API key OpenAI.' }).waitFor();
  assert.equal((await readFile(join(data, 'openai.credential'))).includes(Buffer.from(fakeKey)), false);
  assert.equal(JSON.stringify(await page.evaluate(() => window.orglet.call('workspace', {}))).includes(fakeKey), false);
  await openaiRegion.getByRole('switch').click();
  await page.getByRole('status').filter({ hasText: 'Đã ngắt OpenAI.' }).waitFor();
  const anthropicRegion = page.getByRole('region', { name: 'Kết nối Anthropic', exact: true });
  await anthropicRegion.getByRole('switch').click();
  await anthropicRegion.getByRole('button', { name: 'Từ tệp', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Đã lưu API key Anthropic.' }).waitFor();
  assert.equal((await readFile(join(data, 'anthropic.credential'))).includes(Buffer.from(fakeKey)), false);
  await anthropicRegion.getByRole('switch').click();
  await page.getByRole('status').filter({ hasText: 'Đã ngắt Anthropic.' }).waitFor();
  // Typed-key path: enable the provider, send once to main, never return, clear the draft.
  const typed = 'sk-orglet-typed-fixture-not-a-real-key';
  await openaiRegion.getByRole('switch').click();
  await page.getByLabel('API key OpenAI', { exact: true }).fill(typed);
  await openaiRegion.getByRole('button', { name: 'Lưu key', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Đã lưu API key OpenAI.' }).waitFor();
  // Saved key stays as mask dots in the field (not the real secret) so the user sees it is filled.
  assert.equal(await page.getByLabel('API key OpenAI', { exact: true }).inputValue(), '••••••••••••••••');
  assert.equal((await readFile(join(data, 'openai.credential'))).includes(Buffer.from(typed)), false);
  assert.equal(JSON.stringify(await page.evaluate(() => window.orglet.call('workspace', {}))).includes(typed), false);
  await openaiRegion.getByRole('switch').click();
  await page.getByRole('status').filter({ hasText: 'Đã ngắt OpenAI.' }).waitFor();
  await page.getByRole('tab', { name: 'Chung', exact: true }).click();
  await page.getByRole('combobox', { name: 'Giao diện', exact: true }).click(); await page.getByRole('option', { name: 'Tối', exact: true }).click();
  await page.getByText('Đã lưu.', { exact: true }).waitFor();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark', undefined, { timeout: 5000 });
  await page.screenshot({ path: join(output, 'desktop-dark-settings.png') });
  await page.keyboard.press('Escape');
  await page.evaluate(() => window.orglet.call('createTemplate', { templateId: 'research-review', provider: 'demo' }));
  await page.getByRole('button', { name: 'Research Review', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Research Review', exact: true }).click();
  await page.getByRole('heading', { name: 'Đang nhắn với Research Review' }).waitFor();
  await page.getByRole('button', { name: 'Thiết lập nhóm', exact: true }).click();
  await page.getByRole('dialog', { name: 'Thiết lập nhóm' }).waitFor();
  assert.equal(await page.getByLabel('Tên nhóm', { exact: true }).inputValue(), 'Research Review');
  await page.keyboard.press('Escape');
  await page.getByRole('textbox', { name: 'Tin nhắn' }).fill('Desktop smoke: team synthesis');
  await page.getByRole('button', { name: 'Gửi tin nhắn', exact: true }).click();
  await page.locator('.chat-reply, .report').first().waitFor();
  const teamTask = (await page.evaluate(() => window.orglet.call('workspace', {}))).tasks[0];
  const teamDetail = await page.evaluate(id => window.orglet.call('task', { id }), teamTask.id);
  assert.equal(teamDetail.task.status, 'completed'); assert.equal(teamDetail.artifacts.length, 3);
  assert.equal(teamDetail.runs.filter(run => run.stage === 'synthesis').length, 1);
  await page.getByRole('button', { name: 'Chi tiết', exact: true }).click();
  await page.locator('details').first().locator('summary').click();
  await page.getByRole('button', { name: 'Xuất báo cáo này', exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: /^Công việc mới/ }).click();
  const datasetPath = join(data, 'dataset.csv'); await writeFile(datasetPath, 'id,label\n1,a\n2,b\n2,c\n');
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, datasetPath);
  await page.getByRole('button', { name: 'Thêm nguồn', exact: true }).click(); await page.getByRole('menuitem', { name: /^Tệp/ }).click();
  await page.getByText('dataset.csv', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).fill('Desktop smoke: deterministic dataset checker');
  await page.getByRole('button', { name: 'Gửi công việc', exact: true }).click();
  await page.locator('.chat-reply, .report').first().waitFor();
  await page.getByRole('button', { name: '1 nguồn', exact: true }).click();
  await page.getByRole('checkbox', { name: 'dataset.csv', exact: true }).check();
  await page.getByLabel('Cột ID (không bắt buộc)').fill('id');
  await page.getByRole('button', { name: 'Chạy checker local', exact: true }).click();
  await page.locator('summary').filter({ hasText: 'Kết quả checker' }).click({ timeout: 25_000 });
  await page.getByText('3 dòng · 2 cột', { exact: true }).waitFor();
  await page.getByText('ID id: 0 null, 1 dòng trùng ID không null.', { exact: true }).waitFor();
  await page.screenshot({ path: join(output, 'desktop-checker.png') });
  const checkedTask = (await page.evaluate(() => window.orglet.call('workspace', {}))).tasks[0];
  const checkedDetail = await page.evaluate(id => window.orglet.call('task', { id }), checkedTask.id);
  assert.equal(checkedDetail.profiles.length, 1); assert.equal(checkedDetail.profiles[0].result.datasets[0].rows, 3);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: /^Công việc mới/ }).click();
  for (const name of ['first', 'second']) {
    const folder = join(data, name); await mkdir(folder);
    await writeFile(join(folder, `${name}.txt`), 'Folder evidence'); await writeFile(join(folder, `${name}.bin`), 'Unsupported fixture');
    await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, folder);
    await page.getByRole('button', { name: 'Thêm nguồn', exact: true }).click(); await page.getByRole('menuitem', { name: /^Thư mục/ }).click();
    await page.getByText(`${name}.txt`, { exact: true }).waitFor();
  }
  await page.getByText('2 mục không được thêm vào task', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Nội dung công việc' }).fill('Desktop smoke: two folders');
  await page.getByRole('button', { name: 'Gửi công việc', exact: true }).click();
  await page.locator('.chat-reply, .report').first().waitFor();
  const folderTask = (await page.evaluate(() => window.orglet.call('workspace', {}))).tasks[0];
  assert.equal(folderTask.excludedSources.length, 2); assert.equal(folderTask.sourceIds.length, 2);
  const pausedTaskId = await page.evaluate(async () => {
    const workspace = await window.orglet.call('workspace', {});
    const id = await window.orglet.call('createTask', { workerId: workspace.workers.find(worker => worker.provider === 'demo').id, brief: 'Desktop smoke: pause and resume', sourceIds: [], consent: false, budgetMicros: 1000 });
    await window.orglet.call('pause', { id }); return id;
  });
  await page.getByRole('button', { name: /^Desktop smoke: pause and resume/ }).click();
  await page.getByRole('button', { name: 'Tiếp tục từ checkpoint', exact: true }).waitFor();
  const pausedRunId = (await page.evaluate(id => window.orglet.call('task', { id }), pausedTaskId)).runs[0].id;
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1024, 768));
  await page.screenshot({ path: join(output, 'desktop-1024.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(2));
  await page.getByRole('button', { name: 'Mở sidebar', exact: true }).waitFor();
  const zoomCapture = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));
  await writeFile(join(output, 'desktop-zoom-200.png'), Buffer.from(zoomCapture, 'base64'));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await app.close(); app = await launch();
  const reopened = await app.firstWindow(); await useVietnamese(reopened);
  if (await reopened.getByRole('button', { name: 'Mở sidebar', exact: true }).count()) await reopened.getByRole('button', { name: 'Mở sidebar', exact: true }).click();
  await reopened.getByRole('button', { name: /^Desktop smoke: persistent task/ }).click();
  await reopened.locator('.chat-reply, .report').first().waitFor();
  const restored = await reopened.evaluate(id => window.orglet.call('task', { id }), taskId);
  const restoredFolders = await reopened.evaluate(id => window.orglet.call('task', { id }), folderTask.id);
  assert.deepEqual(restoredFolders.task.excludedSources, folderTask.excludedSources);
  assert.equal(restored.artifacts.length, 1); assert.equal(restored.artifacts[0].report.format, 'chat'); assert.equal(restored.task.status, 'completed');
  if (await reopened.getByRole('button', { name: 'Mở sidebar', exact: true }).count()) await reopened.getByRole('button', { name: 'Mở sidebar', exact: true }).click();
  await reopened.getByRole('button', { name: /^Desktop smoke: pause and resume/ }).click();
  await reopened.getByRole('button', { name: 'Tiếp tục từ checkpoint', exact: true }).click();
  await reopened.locator('.chat-reply, .report').first().waitFor();
  const resumed = await reopened.evaluate(id => window.orglet.call('task', { id }), pausedTaskId);
  assert.equal(resumed.task.status, 'completed'); assert.equal(resumed.runs.length, 1); assert.equal(resumed.runs[0].id, pausedRunId);
  assert.deepEqual(errors, []);
  const result = { native, sqliteVersion: state.sqliteVersion, persistedTaskId: taskId, artifactsAfterRestart: restored.artifacts.length, rendererErrors: errors, dataDirectory: data };
  await writeFile(join(output, 'desktop-smoke.json'), JSON.stringify(result, null, 2)); console.log(JSON.stringify(result, null, 2));
} catch (error) {
  if (app) { const pages = app.windows(); if (pages[0]) await pages[0].screenshot({ path: join(output, 'desktop-failure.png') }).catch(() => {}); }
  throw error;
} finally { if (app) await app.close(); }

